from __future__ import annotations
import argparse
import json
import sys
from rich.console import Console
from aiact.questionnaire import QuestionnaireRunner
from aiact.engine import ClassificationEngine
from aiact import fuzzy
from aiact.formatter import ResultFormatter

BANNER = """
╔══════════════════════════════════════════════════════╗
║     EU AI Act Risk Classification Tool               ║
║     Identifies the risk tier of your AI system       ║
╚══════════════════════════════════════════════════════╝

DISCLAIMER: This tool and its classification rules were generated by AI.
It is intended as a starting point only and does not constitute legal advice.
Always verify results with a qualified legal expert.

Answer each question about your AI system.
Use the numbered choices — "Not sure" is always valid.
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Classify an AI system under the EU AI Act risk tiers."
    )
    parser.add_argument("--json", action="store_true", help="Output result as JSON")
    parser.add_argument("--no-color", action="store_true", help="Disable coloured output")
    args = parser.parse_args()

    console = Console(no_color=args.no_color)

    if not args.json:
        console.print(BANNER, style="bold cyan")

    runner = QuestionnaireRunner()
    try:
        answers = runner.run()
    except SystemExit:
        sys.exit(0)

    profile = runner.build_profile(answers)
    engine = ClassificationEngine()
    matches = engine.classify(profile)
    result = fuzzy.aggregate_results(matches)

    if args.json:
        print(result.model_dump_json(indent=2))
    else:
        console.print("\n[bold]── Classification Result ──[/bold]\n")
        formatter = ResultFormatter(no_color=args.no_color)
        formatter.display_result(result)


if __name__ == "__main__":
    main()
