from __future__ import annotations
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich import box
from aiact.models import ClassificationResult

TIER_COLORS = {
    "UNACCEPTABLE": "bold red",
    "HIGH":         "bold yellow",
    "LIMITED":      "bold cyan",
    "MINIMAL":      "bold green",
}

TIER_LABELS = {
    "UNACCEPTABLE": "UNACCEPTABLE RISK — PROHIBITED",
    "HIGH":         "HIGH RISK",
    "LIMITED":      "LIMITED RISK — Transparency Obligations",
    "MINIMAL":      "MINIMAL / NO RISK",
}

TIER_DESCRIPTIONS = {
    "UNACCEPTABLE": (
        "This AI system falls under a prohibited practice under Art. 5 of the EU AI Act. "
        "Such systems are banned from being placed on the EU market or put into service."
    ),
    "HIGH": (
        "This AI system is classified as high-risk under Annex III of the EU AI Act. "
        "It must comply with requirements on risk management, data governance, technical documentation, "
        "transparency, human oversight, accuracy, robustness, and cybersecurity (Art. 9-15). "
        "Registration in the EU database and conformity assessment are required before deployment."
    ),
    "LIMITED": (
        "This AI system has limited risk but is subject to transparency obligations under Art. 50. "
        "Users must be informed when interacting with AI, and synthetic content must be labelled."
    ),
    "MINIMAL": (
        "This AI system presents minimal or no specific risk under the EU AI Act. "
        "No specific compliance obligations apply, though general EU law (GDPR, product safety) may still be relevant."
    ),
}


def _confidence_bar(confidence: float, width: int = 20) -> str:
    filled = round(confidence * width)
    return "█" * filled + "░" * (width - filled)


class ResultFormatter:
    def __init__(self, no_color: bool = False) -> None:
        self._console = Console(highlight=False, no_color=no_color)

    def display_result(self, result: ClassificationResult) -> None:
        console = self._console
        color = TIER_COLORS.get(result.primary_tier, "bold white")
        label = TIER_LABELS.get(result.primary_tier, result.primary_tier)
        description = TIER_DESCRIPTIONS.get(result.primary_tier, "")

        pct = int(result.primary_confidence * 100)
        bar = _confidence_bar(result.primary_confidence)

        title = Text(f" {label} ", style=color)
        body_lines = [
            Text(description),
            Text(""),
            Text(f"Confidence: {bar} {pct}%", style="dim"),
        ]

        if result.uncertainty_note:
            body_lines.append(Text(""))
            body_lines.append(Text(f"⚠  {result.uncertainty_note}", style="yellow"))

        body = Text("\n").join(body_lines)
        console.print(Panel(body, title=title, border_style=color.split()[1] if " " in color else color, box=box.DOUBLE))

        # Matched rules table
        if result.all_matches:
            table = Table(title="Matched Rules", box=box.SIMPLE_HEAVY, show_lines=True)
            table.add_column("Rule ID", style="dim", no_wrap=True)
            table.add_column("Tier", no_wrap=True)
            table.add_column("Article", no_wrap=True)
            table.add_column("Reason")
            table.add_column("Conf.", no_wrap=True, justify="right")

            for m in sorted(result.all_matches, key=lambda x: (-x.confidence, x.risk_tier)):
                tier_color = TIER_COLORS.get(m.risk_tier, "white").split()[-1]
                table.add_row(
                    m.rule_id,
                    Text(m.risk_tier, style=TIER_COLORS.get(m.risk_tier, "")),
                    m.article,
                    m.reason,
                    f"{int(m.confidence * 100)}%",
                )
            console.print(table)

        # Secondary obligations
        if result.secondary_obligations:
            console.print()
            console.print("[bold]Additional obligations:[/bold]")
            for obl in result.secondary_obligations:
                console.print(f"  • {obl}")

        console.print()
        console.print(
            "[dim]Disclaimer: This tool and its classification rules were generated by AI. "
            "Results are for informational purposes only and do not constitute legal advice. "
            "Consult a qualified legal expert before making compliance decisions.[/dim]"
        )
        console.print()
